import Phaser from "phaser";
import { BROWN_BOX_PALETTE } from "./BrownBoxTheme";

export type PixelSprite = readonly string[];

const sprite = (source: string): PixelSprite =>
  Object.freeze(source.trim().split("\n"));

export const FLUXBALL_CLASSIC_SPRITES = Object.freeze({
  A: sprite(`
....................
....................
.......CCCCCC.......
.......CCCCCC.......
.......CCCCCC.......
.......CCCCCC.......
.......CCCCCC.......
....................
.......CCCCCC.......
.......CCCCCC.......
.......CCCCCCC......
......CCCCCCC.C.....
....CC.CCCCCC..CC...
...C...CCCCCC....C..
........C...C.......
.......C.....C......
.......C.....C......
......C.......C.....
......C.......C.....
....................`),
  B: sprite(`
....................
....................
.........CC.........
........CCCC........
.......CCCCCC.......
.......CCCCCC.......
........CCCC........
.........CC.........
.........CCC........
........CCCCC.......
.......CCCCCCC......
......CCCCCCCCC.....
....CCCCCCCCCCCCC...
...C.CCCCCCCCCCC.C..
........C...C.......
.......C.....C......
.......C.....C......
......C.......C.....
......C.......C.....
....................`),
  C: sprite(`
....................
....................
......CCCCCCCC......
......CCCCCCCC......
......CCCCCCCC......
......CCCCCCCC......
......CCCCCCCC......
....................
.....CCCCCCCCCCC....
......CCCCCCCCC.....
.......CCCCCCC......
......C.CCCCC.C.....
....CC..CCCCC..CC...
...C....CCCCC....C..
........C.C.C.......
.......C.....C......
.......C.....C......
......C.......C.....
......C.......C.....
....................`),
  D: sprite(`
....................
....................
.........CC.........
........CCCC........
.......CCCCCC.......
.......CCCCCC.......
........CCCC........
.........CC.........
......CCCCCCCC......
......CCCCCCCC......
......CCCCCCCC......
......CCCCCCCCC.....
....CCCCCCCCCC.CC...
...C..CCCCCCCC...C..
........C...C.......
.......C.....C......
.......C.....C......
......C.......C.....
......C.......C.....
....................`),
});

export const FLUXBALL_CLASSIC_BALL = sprite(`
....................
....................
.......CCCCCC.......
......CCCCCCCC......
....CCCC....CCCC....
....CC........CC....
...CC..........CC...
..CCC..........CCC..
..CC............CC..
..CC.....CC.....CC..
..CC.....CC.....CC..
..CC............CC..
..CCC..........CCC..
...CC..........CC...
....CC........CC....
....CCCC....CCCC....
......CCCCCCCC......
.......CCCCCC.......
....................
....................`);

export const FLUXBALL_V2_BALL = sprite(`
..CCCC..
.C....C.
C.C..C.C
C......C
C......C
C.C..C.C
.C....C.
..CCCC..`);

export const SKIPIXL_SPRITES = Object.freeze({
  hardLeft: sprite(`
.........CC..
.......CCCC..
......CCCC...
...C..CC.C...
....CCCC.....
...CCCC......
...C.C.......
..C..C.......
.C...C.......
C....C.......
CC....CC.....
.CC....CC....`),
  left: sprite(`
......CC.....
.....CCCC....
.....CCC.....
..C..CC.C....
...C.CCC.....
....CCCC.....
....C.C......
...C..C......
..C...C......
.C....C......
.C.....C.....
C......C.....`),
  softLeft: sprite(`
.....CC.....
....CCCC....
....CCC.....
.C..CC..C...
..C.CC.C....
...CCCC.....
...C..C.....
..C...C.....
..C...C.....
.C....C.....
.C.....C....
C......C....`),
  neutral: sprite(`
....CC....
...CCCC...
...CCCC...
C...CC...C
.C..CC..C.
..CCCCCC..
...C..C...
...C..C...
..C....C..
..C....C..
.C......C.
.C......C.`),
  softRight: sprite(`
.....CC.....
....CCCC....
.....CCC....
...C..CC..C.
....C.CC.C..
.....CCCC...
.....C..C...
.....C...C..
.....C...C..
.....C....C.
....C.....C.
....C......C`),
  right: sprite(`
.....CC......
....CCCC.....
.....CCC.....
....C.CC..C..
.....CCC.C...
.....CCCC....
......C.C....
......C..C...
......C...C..
......C....C.
.....C.....C.
.....C......C`),
  hardRight: sprite(`
..CC.........
..CCCC.......
...CCCC......
...C.CC..C...
.....CCCC....
......CCCC...
.......C.C...
.......C..C..
.......C...C.
.......C....C
.....CC....CC
....CC....CC.`),
  fall: sprite(`
...............
..CC...........
.CCCC..CCCC....
..CC.CCCCCCC...
...CCCC..CCC...
..CC..C....CC..
.C.....C.....C.
C......C......C`),
  recovery: sprite(`
....CC....
...CCCC...
...CCCC...
..C.CC.C..
.C..CC..C.
...CCCC...
...C..C...
..C....C..
.C......C.
C........C`),
});

export const QUANTMAN_PLAYER = sprite(`
................
....CCCCCCCC....
...CCCCCCCCCC...
..CCCCCCCCCCCC..
.CCCCCDDCCCCCCC.
.CCCCCDDCCCCCCC.
.CCCCCCCC.......
.CCCCCCCC.......
.CCCCCCCC.......
.CCCCCCCC.......
.CCCCCCCCCCCCCC.
.CCCCCCCCCCCCCC.
..CCCCCCCCCCCC..
...CCCCCCCCCC...
....CCCCCCCC....
................`);

export const QUANTMAN_GHOST = sprite(`
................
................
.....CCCCCC.....
.....CCCCCC.....
...CCCCCCCCCC...
...CCCCCCCCCC...
..CCCCCCCCCCCC..
..CCCDDCCDDCCC..
..CCCDDCCDDCCC..
..CCCCCCCCCCCC..
..CCCCCCCCCCCC..
..CCCCCCCCCCCC..
..CCCCCCCCCCCC..
...CCCC..CCCC...
...CCCC..CCCC...
................`);

export const QUANTMAN_FRAGMENT = sprite(`
....C...
...CCC..
...CCC..
..CTTCC.
.CCTTCCC
..CCCCC.
...CCC..
....C...`);

export interface PixelSpriteOptions {
  readonly pixel: number;
  readonly centerX: number;
  readonly bottomY: number;
  readonly cream?: number;
  readonly tan?: number;
  readonly dark?: number;
}

export function rotatePixelSprite(
  pattern: PixelSprite,
  quarterTurnsClockwise: number,
): PixelSprite {
  let rows = [...pattern];
  const turns = ((quarterTurnsClockwise % 4) + 4) % 4;
  for (let turn = 0; turn < turns; turn += 1) {
    const height = rows.length;
    const width = rows.reduce(
      (maximum, row) => Math.max(maximum, row.length),
      0,
    );
    rows = Array.from({ length: width }, (_, row) =>
      Array.from(
        { length: height },
        (_, column) => rows[height - 1 - column]?.[row] ?? ".",
      ).join(""),
    );
  }
  return Object.freeze(rows);
}

export function drawPixelSprite(
  graphics: Phaser.GameObjects.Graphics,
  pattern: PixelSprite,
  options: PixelSpriteOptions,
): void {
  const width = pattern.reduce(
    (maximum, row) => Math.max(maximum, row.length),
    0,
  );
  const left = Math.round(options.centerX - (width * options.pixel) / 2);
  const top = Math.round(options.bottomY - pattern.length * options.pixel);
  const colours: Readonly<Record<string, number>> = {
    C: options.cream ?? BROWN_BOX_PALETTE.cream,
    T: options.tan ?? BROWN_BOX_PALETTE.mutedTan,
    D: options.dark ?? BROWN_BOX_PALETTE.darkTobacco,
  };

  for (let row = 0; row < pattern.length; row += 1) {
    const source = pattern[row] ?? "";
    let column = 0;
    while (column < source.length) {
      const token = source[column] ?? ".";
      if (token === ".") {
        column += 1;
        continue;
      }
      let end = column + 1;
      while (end < source.length && source[end] === token) end += 1;
      const colour = colours[token];
      if (colour !== undefined) {
        graphics
          .fillStyle(colour, 1)
          .fillRect(
            left + column * options.pixel,
            top + row * options.pixel,
            (end - column) * options.pixel,
            options.pixel,
          );
      }
      column = end;
    }
  }
}
