import type { ShippedArcadeCabinetId } from "../games/registry";

// Adapted from Story tutorials for repeat play; mode differences belong here.
// Fluxball and Quarry have no finished Story tutorial copy yet.
export const ARCADE_INSTRUCTIONS: Readonly<
  Record<ShippedArcadeCabinetId, readonly string[]>
> = {
  qong: [
    "EACH ROUND USES ONE OF TWO RULES: SCORE THROUGH THE OTHER GOAL, OR YOUR OWN.",
    "A GOAL REVEALS THE UNRESOLVED RULE.",
    "THREE SHARED REVEALS ACROSS SEVEN ROUNDS.",
    "MOVE: W/S OR D-PAD. REVEAL: SPACE / A. P2: ARROWS, ENTER / A.",
  ],
  skipixl: [
    "GET TO THE BOTTOM BEFORE THE TIMER RUNS OUT. PASS THROUGH THE GATES.",
    "MISSED GATES AND COLLISIONS ADD TIME.",
    "TURN: A/D OR D-PAD. BOOST: S OR DOWN.",
  ],
  quantman: [
    "CLEAR THE MAZE. EAT THE DOTS. AVOID THE GHOSTS.",
    "HOLD: WHAT YOU FACE STAYS AS IT IS. LOOK AWAY AND IT MIGHT NOT STAY.",
    "INVERT: A STEADY LOOK FLIPS THE PASSAGE YOU FACE.",
    "MOVE: WASD OR D-PAD. YOUR GAZE FOLLOWS YOUR FACING.",
  ],
  fluxball: [
    "SCORE GOALS. THE RULE DECIDES WHO GETS THE POINT.",
    "SHARED: EVERYONE USES ONE RULE SET. SPLIT: EACH PLAYER HAS THEIR OWN.",
    "PRESS SPACE / A TO CHANGE RULES. ONE CHANGE PER ROUND, SHARED BY ALL PLAYERS.",
    "MOVE: WASD OR D-PAD. WIN THE MOST ROUNDS.",
  ],
  quarry: [
    "READ THE HUNTS AT THE TOP. CATCH YOUR PREY FROM ABOVE. MOST CATCHES WINS THE ROUND.",
    "THE SCREEN PULSES WHEN THE HUNTS CHANGE. CHECK WHO YOU CAN CATCH NOW.",
    "MOVE: A/D OR D-PAD. FLAP: SPACE / A.",
  ],
};
