import type { ShippedArcadeCabinetId } from "../games/registry";

// Adapted from Story tutorials for repeat play; mode differences belong here.
// Fluxball and Quarry have no finished Story tutorial copy yet.
export const ARCADE_INSTRUCTIONS: Readonly<
  Record<ShippedArcadeCabinetId, readonly string[]>
> = {
  qong: [
    "EACH ROUND USES ONE OF TWO RULES.",
    "OPPOSITE: SCORE THROUGH THE OTHER GOAL.",
    "OWN: SCORE THROUGH YOUR OWN GOAL.",
    "THE RULE BEGINS UNRESOLVED.",
    "PRESS ACTION TO OBSERVE THE RULE.",
    "YOU GET THREE OBSERVATIONS ACROSS SEVEN ROUNDS.",
    "OTHERWISE, YOU'LL HAVE TO WAIT FOR A GOAL TO FIND OUT WHO SCORED.",
  ],
  skipixl: [
    "GET TO THE BOTTOM BEFORE THE TIMER RUNS OUT. PASS THROUGH THE GATES.",
    "LEFT / RIGHT: TURN.\nDOWN: GO FASTER.",
    "MISSED GATES AND COLLISIONS ADD TIME. TRY TO SET THE FASTEST TIME.",
  ],
  quantman: [
    "CLEAR THE MAZE. EAT THE DOTS. AVOID THE GHOSTS.",
    "HOLD: WHAT YOU FACE STAYS AS IT IS. LOOK AWAY AND IT MIGHT NOT STAY. USE YOUR GAZE TO HOLD A ROUTE OPEN OR KEEP A WALL CLOSED.",
    "INVERT: A STEADY LOOK FLIPS THE PASSAGE YOU FACE.",
    "YOUR GAZE FOLLOWS YOUR DIRECTION.",
    "CLEAR A MAZE TO EARN ONE EXTRA LIFE AND CONTINUE TO THE NEXT.",
  ],
  fluxball: [
    "THREE RULES CAN CHANGE.",
    "MOVEMENT: YOUR DIRECTIONS MAY BE INVERTED.",
    "BALL: KICK OR CARRY.",
    "GOAL: SCORE THROUGH YOUR OWN OR THE OPPOSITE GOAL.",
    "SHARED: EVERYONE USES THE SAME RULES.",
    "SPLIT: EACH PLAYER HAS THEIR OWN.",
    "ONCE PER ROUND, YOU CAN PRESS ACTION TO CHANGE THE RULES.",
    "MOST GOALS WINS THE ROUND. MOST ROUNDS WINS THE MATCH.",
  ],
  quarry: [
    "CHECK THE HUNTS AT THE TOP: WHO CAN YOU CATCH? WHO CAN CATCH YOU?",
    "LAND ON YOUR PREY FROM ABOVE. KEEP YOUR PREDATORS FROM LANDING ON YOU.",
    "LEFT / RIGHT: MOVE. ACTION: FLAP.",
    "WHEN THE SCREEN PULSES, CHECK AGAIN. THE HUNTS HAVE CHANGED.",
    "MOST CATCHES WINS THE ROUND. MOST ROUNDS WINS THE MATCH.",
  ],
};
