import type { ShippedArcadeCabinetId } from "../games/registry";

// Adapted from Story tutorials for repeat play; mode differences belong here.
// Fluxball and Quarry have no finished Story tutorial copy yet.
export const ARCADE_INSTRUCTIONS: Readonly<
  Record<ShippedArcadeCabinetId, readonly string[]>
> = {
  qong: [
    "EACH ROUND USES ONE OF TWO RULES: SCORE THROUGH THE OTHER GOAL, OR YOUR OWN.",
    "A GOAL REVEALS THE UNRESOLVED RULE.",
    "PRESS SPACE / A TO OBSERVE EARLY. THREE OBSERVATIONS ACROSS SEVEN ROUNDS.",
    "W / S OR STICK: MOVE. P2: UP / DOWN.",
  ],
  skipixl: [
    "GET TO THE BOTTOM BEFORE THE TIMER RUNS OUT. PASS THROUGH THE GATES.",
    "MISSED GATES AND COLLISIONS ADD TIME.",
    "LEFT / RIGHT OR STICK: TURN. DOWN: GO FASTER.",
  ],
  quantman: [
    "CLEAR THE MAZE. EAT THE DOTS. AVOID THE GHOSTS.",
    "HOLD: WHAT YOU FACE STAYS AS IT IS. LOOK AWAY AND IT MIGHT NOT STAY.",
    "INVERT: A STEADY LOOK FLIPS THE PASSAGE YOU FACE.",
    "DIRECTION KEYS OR STICK: MOVE. YOUR GAZE FOLLOWS YOUR FACING.",
  ],
  fluxball: [
    "SCORE GOALS. THE RULE DECIDES WHO GETS THE POINT.",
    "SHARED: EVERYONE USES ONE RULE SET. SPLIT: EACH PLAYER HAS THEIR OWN.",
    "PRESS SPACE / A TO CHANGE RULES. ONE CHANGE PER ROUND, SHARED BY ALL PLAYERS.",
    "PLAYER KEYS OR STICK: MOVE. WIN THE MOST ROUNDS.",
  ],
  quarry: [
    "READ THE HUNTS AT THE TOP. CATCH YOUR PREY FROM ABOVE. MOST CATCHES WINS THE ROUND.",
    "THE SCREEN PULSES WHEN THE HUNTS CHANGE. CHECK WHO YOU CAN CATCH NOW.",
    "LEFT / RIGHT OR STICK: MOVE. SPACE / A: FLAP.",
  ],
};
