import { createRunContext, type RunContext } from "../core/run";
import { createFluxballDesignerEvidence } from "../games/fluxball/FluxballDesignerEvidence";
import { FluxballSession } from "../games/fluxball/FluxballSession";
import { FLUXBALL_PLAYABLE_RULE_BANK } from "../games/fluxball/fluxballControlPacks";
import type {
  FluxballHumanInput,
  FluxballSnapshot,
} from "../games/fluxball/types";
import { QUANTMAN_CONTROL_PACK } from "../games/quantman/quantmanControlPack";
import { pointCell, QuantmanSession } from "../games/quantman/QuantmanSession";
import {
  initialQuantmanTopologyState,
  quantmanDoorIsOpen,
  tryObserveQuantmanTopology,
} from "../games/quantman/QuantmanTopology";
import {
  createQuantmanTopologyTutorialEvidence,
  shortestQuantmanPath,
} from "../games/quantman/QuantmanTopologyEvidence";
import type {
  QuantmanInput,
  QuantmanPackPayload,
  QuantmanSnapshot,
} from "../games/quantman/types";

const QUANTMAN_FIXTURE_TRANSITIONS = 1;
import {
  createSkiPixlDesignerEvidence,
  selectStorySkiPixlPack,
} from "../games/skipixl/SkiPixlCourseAdapter";
import type { SkiPixlSnapshot } from "../games/skipixl/types";
import type { TutorialStartRequest } from "../tutorials/registry";

export type DevDesignerGameId = "skipixl" | "fluxball" | "quantman";

export interface DevDesignerEncounterFixture {
  readonly request: TutorialStartRequest;
  readonly evidenceNote: string;
}

export function createDevDesignerEncounterFixture(
  gameId: DevDesignerGameId,
): DevDesignerEncounterFixture {
  switch (gameId) {
    case "skipixl":
      return createSkiPixlFixture();
    case "fluxball":
      return createFluxballFixture();
    case "quantman":
      return createQuantmanFixture();
  }
}

function createSkiPixlFixture(): DevDesignerEncounterFixture {
  const pack = selectStorySkiPixlPack(0);
  const context = createRunContext({
    gameId: "skipixl",
    storyStage: "skipixl",
    playMode: "story",
    rulesVersion: pack.rulesVersion,
    runSeed: 0,
    pack: packIdentity(pack),
  });
  return Object.freeze({
    request: Object.freeze({
      gameId: "skipixl",
      evidenceInput: Object.freeze({
        origin: "development-fixture",
        context,
        snapshot: completedSkiPixlSnapshot(pack),
        evidence: createSkiPixlDesignerEvidence(pack),
        payload: pack.payload,
      }),
    }),
    evidenceNote:
      "Visual replay fixture using the first installed three-segment IBM Fez QPixl pack; it grants no Story progress.",
  });
}

function createFluxballFixture(): DevDesignerEncounterFixture {
  const pack = FLUXBALL_PLAYABLE_RULE_BANK;
  const context = createRunContext({
    gameId: "fluxball",
    storyStage: "fluxball-four",
    playMode: "story",
    rulesVersion: pack.rulesVersion,
    runSeed: 0,
    pack: packIdentity(pack),
  });
  const session = new FluxballSession(context, {
    competitorCount: 4,
    ruleMode: "individual",
    roundSeconds: 60,
    humanPlayerIds: ["A"],
  });
  let snapshot = session.snapshot();
  const neutralInput: FluxballHumanInput = Object.freeze({ players: {} });
  for (let round = 0; round < 4; round += 1) {
    while (snapshot.phase === "active") {
      snapshot = session.step(neutralInput);
    }
    if (snapshot.phase !== "reveal") {
      throw new Error("Fluxball visual fixture did not reach round reveal.");
    }
    snapshot = session.continueAfterReveal();
  }
  if (snapshot.phase !== "complete") {
    throw new Error("Fluxball visual fixture did not complete four rounds.");
  }
  return Object.freeze({
    request: Object.freeze({
      gameId: "fluxball",
      evidenceInput: Object.freeze({
        origin: "development-fixture",
        context,
        snapshot,
        evidence: createFluxballDesignerEvidence(
          pack,
          snapshot as FluxballSnapshot,
        ),
      }),
    }),
    evidenceNote:
      "Visual replay fixture generated by an actual four-round offline QGraph-bank session; it grants no Story progress.",
  });
}

function createQuantmanFixture(): DevDesignerEncounterFixture {
  const pack = QUANTMAN_CONTROL_PACK;
  const context = createRunContext({
    gameId: "quantman",
    storyStage: "quantman",
    playMode: "story",
    rulesVersion: pack.rulesVersion,
    runSeed: 3,
    pack: packIdentity(pack),
  });
  const payload = quantmanQualificationPayload(pack.payload, context.runSeed);
  const session = new QuantmanSession(context, payload);
  let snapshot = session.snapshot();
  for (
    let observation = 0;
    observation < QUANTMAN_FIXTURE_TRANSITIONS;
    observation += 1
  ) {
    snapshot = session.step({ x: 0, y: 0, observe: true });
    if (snapshot.observationCount !== observation + 1) {
      throw new Error(
        `Quantman visual fixture could not record observation ${observation + 1}.`,
      );
    }
  }
  for (let tick = 0; tick < 1_200 && snapshot.phase === "active"; tick += 1) {
    snapshot = session.step(quantmanAutopilotInput(payload, snapshot));
  }
  if (
    snapshot.phase !== "won" ||
    !snapshot.storyQualified ||
    snapshot.exploitedObservationIndices.length === 0
  ) {
    throw new Error(
      "Quantman visual fixture did not complete an observed Story run.",
    );
  }
  return Object.freeze({
    request: Object.freeze({
      gameId: "quantman",
      evidenceInput: Object.freeze({
        origin: "development-fixture",
        context,
        snapshot,
        payload,
        evidence: createQuantmanTopologyTutorialEvidence(payload, snapshot),
      }),
    }),
    evidenceNote:
      "Visual replay fixture generated by an actual observed Labyrinth-derived Story run; it grants no Story progress.",
  });
}

function quantmanQualificationPayload(
  base: QuantmanPackPayload,
  runSeed: RunContext["runSeed"],
): QuantmanPackPayload {
  const initial = initialQuantmanTopologyState(base, runSeed);
  for (let row = 0; row < base.height; row += 1) {
    for (let col = 0; col < base.width; col += 1) {
      if (base.rows[row]?.[col] !== ".") continue;
      const playerStart = Object.freeze({ row, col });
      const selection = tryObserveQuantmanTopology(
        base,
        initial,
        playerStart,
        new Set(),
        runSeed,
        0,
        { x: 1, y: 0 },
      );
      if (!selection) continue;
      const targetDoor = base.topologyDoors.find(
        (door) =>
          Math.abs(door.row - row) + Math.abs(door.col - col) === 1 &&
          !quantmanDoorIsOpen(initial, door) &&
          quantmanDoorIsOpen(selection.state, door),
      );
      if (!targetDoor) continue;
      return {
        ...base,
        playerStart,
        requiredFragments: 1,
        fragments: [
          Object.freeze({
            fragmentId: "qualification-pellet",
            row: targetDoor.row,
            col: targetDoor.col,
            kind: "pellet",
          }),
        ],
        pursuers: base.pursuers,
      };
    }
  }
  throw new Error(
    "Quantman could not build a causal Story qualification fixture.",
  );
}

function completedSkiPixlSnapshot(
  pack: ReturnType<typeof selectStorySkiPixlPack>,
): SkiPixlSnapshot {
  return Object.freeze({
    phase: "complete",
    tick: 3_600,
    readyTicksRemaining: 0,
    elapsedTicks: 3_420,
    elapsedSeconds: 57,
    targetSeconds: pack.payload.winSeconds,
    secondsRemaining: pack.payload.winSeconds - 57,
    distance: pack.payload.courseLength,
    courseLength: pack.payload.courseLength,
    speed: pack.payload.cruiseSpeed,
    skierX: 320,
    lateralVelocity: 0,
    steeringAngle: 0,
    obstaclesResolved: pack.payload.obstacles.length,
    gatesResolved: pack.payload.gates?.length ?? 0,
    gatePenaltyTicks: 0,
    gateResults: Object.freeze([]),
    latestGate: null,
    collisions: Object.freeze([]),
    latestCollision: null,
    knockdownTicksRemaining: 0,
    storyQualified: true,
    finishedUnderPar: false,
    receipt: pack.payload.receipt,
  });
}

function packIdentity(pack: {
  readonly packId: string;
  readonly contentSha256: string;
  readonly schemaVersion: string;
  readonly source: string;
}) {
  return Object.freeze({
    packId: pack.packId,
    contentSha256: pack.contentSha256,
    schemaVersion: pack.schemaVersion,
    source: pack.source,
  });
}

function quantmanAutopilotInput(
  payload: QuantmanPackPayload,
  snapshot: QuantmanSnapshot,
): QuantmanInput {
  const start = pointCell(payload, snapshot.player.x, snapshot.player.y);
  const route = shortestQuantmanPath(snapshot.currentRows, start, payload.exit);
  const next = route?.[1];
  if (!next) return { x: 0, y: 0, observe: false };
  return {
    x: Math.sign(next.col - start.col) as -1 | 0 | 1,
    y: Math.sign(next.row - start.row) as -1 | 0 | 1,
    observe: false,
  };
}
