export const TUNING = {
  fixedStepSeconds: 1 / 20,
  ticksPerSecond: 20,
  roundSeconds: 40,
  roundTicks: 800,
  totalRounds: 4,
  courtWidth: 800,
  courtHeight: 460,
  courtPadding: 24,
  goalHalfHeight: 72,
  horizontalGoalHalfWidth: 120,
  playerRadius: 17,
  ballRadius: 5,
  playerInitialSpeed: 60,
  playerAcceleration: 480,
  playerMaximumSpeed: 165,
  playerReleaseDeceleration: 720,
  playerReversalAcceleration: 960,
  playerCollisionNormalDamping: 0.32,
  strikeBaseSpeed: 250,
  strikeClosingSpeedFactor: 0.6,
  strikeMaximumSpeed: 340,
  carryOffset: 25,
  ballDampingPerTick: 0.975,
  ballStopSpeed: 6,
  contactCooldownTicks: 5,
  carrierChallengeDistance: 37,
  carrierChallengeMinimumClosingSpeed: 8,
  carrierPairCooldownTicks: 14,
  carrierSeparationDistance: 42,
  goalFreezeTicks: 5,
  computerDecisionTicks: 4,
  computerFourPlayerDecisionTicks: 7,
  computerFourPlayerHesitationCycle: 7,
  computerDeadZone: 5,
  maxFrameSeconds: 0.25,
  maxAuditEvents: 512,
} as const;
